### ISSUE TITLE
thriftrw has a wrong error message format

### ISSUE THREAD

**Issue by ShanniLi** [uber/thriftrw#55]
cc: @kriskowal @Raynos @jcorbin
Refer to uber/tchannel#1188

For example:
{ ok: false,
  head: {},
  body: { [ThriftException: invalid service name: ] name: 'ThriftException', serviceName: '' },
  headers: { as: 'thrift' } }

It should be:
{ ok: false,
  head: {},
  body: { message:'invalid service name: ', name: 'ThriftException', serviceName: '' },
  headers: { as: 'thrift' } }

**Comment by Raynos** [comment]
@ShanniLi 

The error is correct. You can see invalid service name. Your getting confused by how node prints errors.

You should just check `body.message` it should be correct.

**Comment by ShanniLi** [comment]
@Raynos indeed!
