### ISSUE TITLE
better i64 support

### ISSUE THREAD

**Issue by blampe** [uber/thriftrw#68]
These should be returned using a bigint type or something. DISCUSS

**Comment by blampe** [comment]
@abhinav @kriskowal @tranminhh @anthonypt87

**Comment by kriskowal** [comment]
Walking down: https://www.npmjs.com/search?q=64+bit+integer

Maybe:

- [node-int64](https://www.npmjs.com/package/node-int64) backs an i64 with a buffer and understands the two numbers representation and provides all the right operators, and is designed for node-thrift and has a browserified version https://www.npmjs.com/package/node-int64-browserify BUT does not name its methods so won’t profile well. could be good for contribute or fork.
- [long](https://github.com/dcodeIO/Long.js/blob/master/src/Long.js) has all the right operators, implemented in javascript, but designed for browsers/closure compiler, and its methods are anonymous so it won't profile well. could be a good place to contribute or fork.

No:

- https://www.npmjs.com/package/int64-native-node12 has some of the necessary operators, but is a binary dependency
- https://www.npmjs.com/package/int2buf can write the 53 bit integer we get from JavaScript numbers into an 8 byte buffer.
- https://www.npmjs.com/package/to-unsigned-int64 〃
- https://www.npmjs.com/package/node-cint64 binary dependency that implements all the right operators
- https://www.npmjs.com/package/node-ffi no
- https://www.npmjs.com/package/liblwes 〃
- https://www.npmjs.com/package/murmur implements some of the right operators, backed by a buffer
- https://www.npmjs.com/package/eightbyte may have the right operators, but does so by duck punching Number.prototype, potential candidate for fork/consolidate

**Comment by Raynos** [comment]
@kriskowal 

For performance i REALLY REALLY want to avoid `buffer.slice(n, n+8)` and pass around `{ hi, lo }`

Also matches eventual language support ( https://gist.github.com/BrendanEich/4294d5c212a6d2254703 )

For this reason I would favor `long`

**Comment by malandrew** [comment]
Google's i64 support is solid. Maybe we can extract it into a standalone library?

https://github.com/google/closure-library/blob/master/closure/goog/math/long.js

**Comment by malandrew** [comment]
Oh wait, looks like long.js is that already. Another +1 for long. I think we just need to contribute changes to eliminate unnamed functions.

**Comment by kriskowal** [comment]
Long.js has added names to all of its functions https://github.com/dcodeIO/Long.js/pull/23, fixed some API inconsistencies I pointed out https://github.com/dcodeIO/Long.js/issues/25, and maybe we will even get support for self-mutating methods to reduce GC https://github.com/dcodeIO/Long.js/issues/24

**Comment by kriskowal** [comment]
In short, we can bring Long.js in as a dependency and expose a `js.type='Long'` annotation to surface i64. To be consistent, we should either add support for `{"high", "low"}` coercion or modify the existing `{"hi", "lo"}` support.

**Comment by Raynos** [comment]
@kriskowal can we open a new task about bumping major and defaulting to long instances
